#define THREAD_SIZE_VAL 256
#define THREAD_SIZE [numthreads(THREAD_SIZE_VAL,1,1)]

#define THREAD_SIZE_LARGE_VAL 1024
#define THREAD_SIZE_LARGE [numthreads(THREAD_SIZE_LARGE_VAL,1,1)]

#define THREAD_SIZE_EDITOR [numthreads(512,1,1)]
